In [27]:
# Import the dependencies

import pandas as pd
import gmaps
import requests

# import the API key

from config import g_key

In [28]:
# Store the CSV you created in part one into a dataframe

city_data_df = pd.read_csv("weather_data/cities.csv")

city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Port Elizabeth,ZA,2022-05-04 15:52:10,-33.9180,25.5701,70.09,83,0,4.61
1,1,Salinopolis,BR,2022-05-04 15:52:10,-0.6136,-47.3561,81.00,80,68,4.36
2,2,East London,ZA,2022-05-04 15:52:11,-33.0153,27.9116,70.74,83,0,4.61
3,3,Ushuaia,AR,2022-05-04 15:52:11,-54.8000,-68.3000,44.22,65,40,20.71
4,4,Kushchevskaya,RU,2022-05-04 15:52:11,46.5564,39.6386,57.65,78,100,4.14

In [29]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [30]:
# Configure gmaps to use your google api key

gmaps.configure(api_key=g_key)

In [31]:
# 1. Assign the locations to an array of latitude and longitude pairs.

locations = [latitude, longitude]

# 2. Assign the weights variable to some values.

temperatures = # an array of length equal to the locations array length

# 3. Assign a figure variable to the gmaps.figure() attribute

fig = gmaps.figure()

# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.

heatmap_layer = gmaps.heatmap_layer(locations, weights=temperatures)

# 5. Add the heatmap layer.

fig.add_layer(heatmap_layer)

# 6. Call the figure to plot the data

fig

SyntaxError: invalid syntax (Temp/ipykernel_27140/1465717285.py, line 7)

In [32]:
# Heatmap of temperature

# Get the latitude and longitude

locations = city_data_df[["Lat","Lng"]]

# Get the maximum temperature

max_temp = city_data_df["Max Temp"]

# Assign the figure variable

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable

heat_layer = gmaps.heatmap_layer(locations, 
                                 weights = [max(temp, 0) for temp in max_temp], 
                                 dissipating=False, max_intensity=300, point_radius = 4)

# Add the heatmap layer.

fig.add_layer(heat_layer)

# Call the figure to plot the data

fig

Figure(layout=FigureLayout(height='420px'))

In [33]:
# Heatmap of humidity

# Get the latitude and longitude

locations = city_data_df[["Lat","Lng"]]

# Get the maximum temperature

humidity = city_data_df["Humidity"]

# Assign the figure variable

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable

heat_layer = gmaps.heatmap_layer(locations, 
                                 weights = humidity, 
                                 dissipating=False, max_intensity=300, point_radius = 3)

# Add the heatmap layer.

fig.add_layer(heat_layer)

# Call the figure to plot the data

fig

Figure(layout=FigureLayout(height='420px'))

In [34]:
# Heatmap of cloudiness

# Get the latitude and longitude

locations = city_data_df[["Lat","Lng"]]

# Get the maximum temperature

clouds = city_data_df["Cloudiness"]

# Assign the figure variable

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable

heat_layer = gmaps.heatmap_layer(locations, 
                                 weights = clouds, 
                                 dissipating=False, max_intensity=300, point_radius = 3)

# Add the heatmap layer.

fig.add_layer(heat_layer)

# Call the figure to plot the data

fig

Figure(layout=FigureLayout(height='420px'))

In [35]:
# Heatmap of wind speed

# Get the latitude and longitude

locations = city_data_df[["Lat","Lng"]]

# Get the maximum temperature

wind_speed = city_data_df["Wind Speed"]

# Assign the figure variable

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable

heat_layer = gmaps.heatmap_layer(locations, 
                                 weights = wind_speed, 
                                 dissipating=False, max_intensity=300, point_radius = 3)

# Add the heatmap layer.

fig.add_layer(heat_layer)

# Call the figure to plot the data

fig

Figure(layout=FigureLayout(height='420px'))

In [36]:
# Ask the customer to add a minimum and maximum temperature value.

min_temp = float(input("What is the minimum temperature you would like for your trip? "))

max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [37]:
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) &
                                      (city_data_df["Max Temp"]>= min_temp)].dropna()

preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
1,1,Salinopolis,BR,2022-05-04 15:52:10,-0.6136,-47.3561,81.00,80,68,4.36
8,8,Puerto Quijarro,BO,2022-05-04 15:52:13,-17.7833,-57.7667,79.90,24,24,4.18
11,11,Caxias,PT,2022-05-04 15:52:14,38.7031,-9.2767,80.42,43,20,21.85
16,16,Axim,GH,2022-05-04 15:52:16,4.8699,-2.2405,85.23,68,43,8.39
19,19,Victoria,HK,2022-05-04 15:50:44,22.2855,114.1577,77.18,77,14,8.01
21,21,Porto Novo,BJ,2022-05-04 15:52:17,6.4965,2.6036,85.98,66,48,11.03
27,27,Trairi,BR,2022-05-04 15:52:20,-3.2778,-39.2689,83.64,75,100,9.89
29,29,Maceio,BR,2022-05-04 15:52:20,-9.6658,-35.7353,87.24,66,75,12.66
54,54,Marsh Harbour,BS,2022-05-04 15:53:29,26.5412,-77.0636,79.12,72,93,7.70
57,57,Arraial Do Cabo,BR,2022-05-04 15:53:30,-22.9661,-42.0278,89.56,89,20,12.66

In [38]:
preferred_cities_df.count()

City_ID       202
City          202
Country       202
Date          202
Lat           202
Lng           202
Max Temp      202
Humidity      202
Cloudiness    202
Wind Speed    202
dtype: int64

In [39]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.

hotel_df = preferred_cities_df[["City","Country","Max Temp","Lat","Lng"]].copy()

hotel_df["Hotel Name"] = ""

hotel_df.head(10)

               City Country  Max Temp      Lat       Lng Hotel Name
1       Salinopolis      BR     81.00  -0.6136  -47.3561
8   Puerto Quijarro      BO     79.90 -17.7833  -57.7667
11           Caxias      PT     80.42  38.7031   -9.2767
16             Axim      GH     85.23   4.8699   -2.2405
19         Victoria      HK     77.18  22.2855  114.1577
21       Porto Novo      BJ     85.98   6.4965    2.6036
27           Trairi      BR     83.64  -3.2778  -39.2689
29           Maceio      BR     87.24  -9.6658  -35.7353
54    Marsh Harbour      BS     79.12  26.5412  -77.0636
57  Arraial Do Cabo      BR     89.56 -22.9661  -42.0278

In [44]:
# Set the parameters to search for a hotel.

params = {
    "radius":5000,
    "type":"lodging",
    "key": g_key}

# Iterate through the dataframe

for index, row in hotel_df.iterrows():
    
    # Get the lat and lng
    
    lat = row["Lat"]
    
    lng = row["Lng"]
    
    # Add the lat and lng to location key for the params dict
    
    params["location"] = f"{lat},{lng}"
    
    # Use the search term: "lodging" and our lat and lng
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search.
    
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    
    try:
    
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    
    except(IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [45]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
1,Salinopolis,BR,81.00,-0.6136,-47.3561,Salinas Park Resort Maçarico AP101
8,Puerto Quijarro,BO,79.90,-17.7833,-57.7667,Hotel palance
11,Caxias,PT,80.42,38.7031,-9.2767,Amazónia Jamor Hotel
16,Axim,GH,85.23,4.8699,-2.2405,Axim Beach Resort And Spa
19,Victoria,HK,77.18,22.2855,114.1577,Mini Hotel Central
21,Porto Novo,BJ,85.98,6.4965,2.6036,Tour Eiffel Hotel Benin
27,Trairi,BR,83.64,-3.2778,-39.2689,janelas do mar
29,Maceio,BR,87.24,-9.6658,-35.7353,Hotel Ponta Verde Maceió
54,Marsh Harbour,BS,79.12,26.5412,-77.0636,Abaco Beach Resort
57,Arraial Do Cabo,BR,89.56,-22.9661,-42.0278,Pousada Porto Praia

In [47]:
# Add a heatmap of temperature for the vacation spots.

locations = hotel_df[["Lat", "Lng"]]

max_temp = hotel_df["Max Temp"]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

marker_layer = gmaps.marker_layer(locations)

fig.add_layer(heat_layer)

fig.add_layer(marker_layer)

# Call the figure to plot the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [48]:
info_box_template = """

<dl>

<dt>Hotel Name</dt><dd>{Hotel Name}</dd>

<dt>City</dt><dd>{City}</dd>

<dt>Country</dt><dd>{Country}</dd>

<dt>Max Temp</dt><dd>{Max Temp} °F</dd>

</dl>

"""

hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [49]:
# Add a heatmap of temperature for the vacation spots.

locations = hotel_df[["Lat", "Lng"]]

max_temp = hotel_df["Max Temp"]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(heat_layer)

fig.add_layer(marker_layer)

# Call the figure to plot the data.

fig

Figure(layout=FigureLayout(height='420px'))